spring:
  application:
    name: SeCause-be
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LOCAL_DB_URL:jdbc:postgresql://localhost:5433/secausedb}
    username: ${LOCAL_DB_USERNAME:postgres}
    password: ${LOCAL_DB_PASSWORD:}
  sql:
    init:
      mode: always
      separator: "@@"
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    prod-server: ${SWAGGER_SERVER_URL:http://localhost:8080}
  api-docs:
    path: /api-docs


github:
  oauth:
    client-id: ${GITHUB_CLIENT_ID:}
    client-secret: ${GITHUB_CLIENT_SECRET:}
    redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:3000/login/callback}

jwt:
  secret: ${JWT_SECRET:secause-local-jwt-secret-key-2026-development-only}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: 1209600000 # 14일
  refresh-secret: ${JWT_REFRESH_SECRET_LOCAL:secause-secret-key-for-local-development-2026}
  refresh-token-hash-secret: ${JWT_REFRESH_HASH_SECRET_LOCAL:secause-hash-secret-key-for-local-development-2026}

fast-api:
  analysis-request-url: ${FASTAPI_ANALYSIS_REQUEST_LOCAL:http://localhost:8001/api/internal/analyze}

analysis:
  callback:
    internal-token: ${ANALYSIS_CALLBACK_INTERNAL_TOKEN:}
